nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~
        skip_same_as_origin: true

# nelmio_cors:
#     defaults:
#         allow_credentials: false
#         allow_origin: ['*']
#         allow_headers: ['*']
#         allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#         expose_headers: []
#         max_age: 3600
#         hosts: []
#         origin_regex: true
#         forced_allow_origin_value: ~
#         skip_same_as_origin: true
    # paths:
    #     '^/admin/':
    #         allow_origin: ['*']
    #         allow_headers: ['*']
    #         allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
    #         max_age: 36000
    #     '^/':
    #         origin_regex: true
    #         allow_origin: ['*']
    #         allow_headers: ['*']
    #         allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
    #         max_age: 36000
    #     '^/api':
    #         origin_regex: true
    #         allow_origin: ['*']
    #         allow_headers: ['*']
    #         allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
    #         max_age: 36000